name: untitled
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '^3.5.3'

dependencies:
   path: ^1.8.0
   http: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.25.4
